services:
  redis:
    image: redis:7-alpine
    container_name: groceryscout-redis

  admin-db:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: groceryscout-admin-db
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
    environment:
      PB_ADMIN_EMAIL: ${PB_ADMIN_EMAIL}
      PB_ADMIN_PASSWORD: ${PB_ADMIN_PASSWORD}
      ENCRYPTION: ${PB_ENCRYPTION_KEY}
    command: ["--encryptionEnv", "ENCRYPTION"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: groceryscout-api
    command: docker/scripts/start_api.sh
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./shared_data:/app/shared_data
      - ./libs:/app/libs
      - ./src/static:/app/src/static
    depends_on:
      redis:
        condition: service_started
      admin-db:
        condition: service_healthy
      llm-matcher:
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: groceryscout-worker
    command: docker/scripts/start_worker.sh
    env_file: .env
    volumes:
      - ./shared_data:/app/shared_data
    depends_on:
      redis:
        condition: service_started
      admin-db:
        condition: service_healthy

  llm-matcher:
    build:
      context: llm_match
      dockerfile: docker/Dockerfile
    container_name: groceryscout-llm-matcher
    volumes:
    - ./libs:/app/libs
    command: docker/scripts/start.sh
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      redis:
        condition: service_started
      admin-db:
        condition: service_healthy
